### ISSUE TITLE
The reproduced results differ too much from those given in the paper

### ISSUE THREAD

**Issue by lizaozhou** [songjiang0909/BoxTaxo#2]
According to the code given, after I ran through it, I found that the results of both the environmental data set and the scientific data set were quite different from those given in the paper.Aside from creating the file, importing the package, and changing the beta value to 0.1(which corresponds to the value given at the end of the paper), I only did two things when debugging the code.
First thing: Added a command to the main.py:parser.add_argument('--model', type=str, default='vec', help='model type')，Used to solve the vec parameter problem in data.py.
The second thing is:When running the main.py, there was an error importing"../data/"+str(dataset)+"/raw/"+str(dataset)+"_raw_en.taxo".In the file downloaded by the platform, the dataset does not have this file. I had to change this to"../data/"+str(dataset)+"/"+str(dataset)+"_all.taxo".I can't get the desired result after only making these changes. Could you please give me some guidance on how to change to get the desired effect?
Science:
![{9TJ~)5MOGN4_1VH5AHEUWE](https://github.com/songjiang0909/BoxTaxo/assets/87571678/0c06f845-b001-4f4f-a427-a98671dba11a)
Environment:
![P4713(_1W)MBV75L5F_%TUB](https://github.com/songjiang0909/BoxTaxo/assets/87571678/ac661d90-6b58-4f9b-95e2-20baa39a59d7)

**Comment by songjiang0909** [comment]
Hi @lizaozhou,

Thanks for providing the details. However, it is quite difficult to figure out what happened only whit this info. Could you please email me (songjiang@cs.ucla.edu) your code so I can help with the debug?  I'm a bit busy by wed but would have this done by this week.

**Comment by lizaozhou** [comment]
Hi@songjiang0909
Thank you for your reply. I will communicate with you by email.

**Comment by songjiang0909** [comment]
Hi @lizaozhou,

Thanks for sharing your code with me. 

The unsatisfactory results are primarily due to incorrect settings. In fact, the "vec" stuff was for my debugging purpose.  I was trying several settings to understand how the model works. I should have removed these debugging codes before, but it was still there for some reason. Apologize for the confusion.

I have updated the code, which fixes both the "vec" stuff and the data path. You should be able to reproduce the results now.
